---

env:
  node: true
  jest/globals: true

parser: babel-eslint

extends:
  - airbnb-base
  - plugin:import/recommended

plugins:
  - jest

rules:
  no-console: 0
  object-curly-newline:
  - error
  - ObjectPattern:
      multiline: true
